<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "data".
 *
 * @property int $id
 * @property string $card_number
 * @property string $date
 * @property double $volume
 * @property string $service
 * @property int $address_id
 */
class Data extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'data';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['volume', 'card_number'], 'required'],
            [['date'], 'safe'],
            [['volume'], 'number'],
            [['address_id'], 'integer'],
            [['card_number'], 'string', 'max' => 20],
            [['service'], 'string', 'max' => 100],
        ];
    }
    public function beforeSave($insert)
    {
        if($this->isNewRecord){
            if ($this->volume > 0){
                $lastInsert = Data::find()->where(['card_number' => $this->card_number])->andFilterWhere(['service' => $this->service])->orderBy(['id'=>SORT_DESC])->one();
                $newValue = $lastInsert->volume  + $this->volume;
                $this->volume = $newValue;
                $this->date  = date('Y-m-d H:i:s');
                $this->service = $lastInsert->service;
                $this->address_id = $lastInsert->address_id;
                $lastInsert->delete();
            }

        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'card_number' => 'Card Number',
            'date' => 'Date',
            'volume' => 'Volume',
            'service' => 'Service',
            'address_id' => 'Address ID',
        ];
    }
}
